# Products
@baseUrl=http://localhost:3000/api

@resourceName=products

# Products

# @name getAllProducts
GET http://localhost:3000/api/products

###

# @name fillterProducts

GET http://localhost:3000/api/products?price_lte=50

###

# @name pagination

GET http://localhost:3000/api/products?_page=1&_limit=5



###

# @name addNewProduct
POST http://localhost:3000/api/products
Content-Type: application/json

{}

###

# @name updateProduct
PATCH http://localhost:3000/api/products/f87be5dd-b8a9-4931-a319-92cffdc0a719
Content-Type: application/json

{
    "thumbnailUrl": "https://cdn.huongnghiepaau.com/wp-content/uploads/2020/02/kem-dua-hau-mat-lanh.jpg"
}


### 

# @name removeProduct
DELETE http://localhost:3000/api/products