# Products
@baseUrl=http://localhost:3000/api

@resourceName=products

# Products

# @name getAllProducts
GET http://localhost:3000/api/products

###

# @name fillterProducts

GET http://localhost:3000/api/products?price_lte=50

###

# @name pagination

GET http://localhost:3000/api/products?_page=1&_limit=5



###

# @name addNewProduct
POST http://localhost:3000/api/products
Content-Type: application/json

{}

###

# @name updateProduct
PATCH {{baseUrl}}/{{resourceName}}/3ad735cd-d6dd-47c2-a001-dbd790d4986c
Content-Type: application/json

{
   "name": "trà ổi",
   "price": 15,
   "thumbnailUrl": "https://cdn.dayphache.edu.vn/wp-content/uploads/2021/03/tra-oi-hong-thoang-thoang-hoa-nhai.jpg"
  
}


### 

# @name removeProduct
DELETE http://localhost:3000/api/products